environment_type: dev

spark:
  app_name: "{{ cookiecutter.project_slug }}-dev"
  config:
    spark.sql.shuffle.partitions: "50"
    spark.sql.adaptive.enabled: "true"
    spark.databricks.delta.preview.enabled: "true"

catalog:
  name: "{{ cookiecutter.catalog_name_dev }}"
  schema_prefix: "{{ cookiecutter.schema_prefix }}"

observability:
  api_key_secret: "monte-carlo/api-key"
  enabled: true

workspace_host: "https://dev.cloud.databricks.com"
