environment_type: lab

spark:
  app_name: "{{ cookiecutter.project_slug }}-lab"
  config:
    spark.sql.shuffle.partitions: "20"
    spark.sql.adaptive.enabled: "true"

catalog:
  name: "lab_analytics"
  schema_prefix: "{{ cookiecutter.schema_prefix }}"

workspace_host: "https://lab.cloud.databricks.com"
