environment_type: prod

spark:
  app_name: "{{ cookiecutter.project_slug }}-prod"
  config:
    spark.sql.shuffle.partitions: "200"
    spark.sql.adaptive.enabled: "true"
    spark.databricks.delta.optimizeWrite.enabled: "true"
    spark.databricks.delta.autoCompact.enabled: "true"

catalog:
  name: "{{ cookiecutter.catalog_name_prod }}"
  schema_prefix: "{{ cookiecutter.schema_prefix }}"

observability:
  api_key_secret: "monte-carlo/api-key-prod"
  enabled: true

workspace_host: "https://prod.cloud.databricks.com"
