name: "{{ cookiecutter.project_slug }}"
version: "1.0.0"
description: "{{ cookiecutter.description }}"
owner_team: "{{ cookiecutter.owner_team }}"

dependencies:
  python_version: "{{ cookiecutter.python_version }}"
  shared_utilities:
    - name: "databricks-utils"
      version: "0.1.0"
      source: "pypi"
  external_packages:
    - "pandas>=2.0.0"
    - "pyarrow>=10.0.0"

metadata:
  git_repository: ""
  git_branch: "main"
  contributors: []
  tags: ["databricks", "medallion", "pipeline"]
  documentation_url: ""
  runbook_url: ""
