environment_type: local

spark:
  app_name: "my-domain-silver-job-local"
  master: "local[*]"
  config:
    spark.sql.session.timeZone: "UTC"
    spark.sql.shuffle.partitions: "4"
    spark.sql.adaptive.enabled: "false"
    spark.sql.warehouse.dir": "spark-warehouse"